altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1750d906-56b4-4295-8aff-27b1e40042ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7690e82a-a1d7-4d00-9dd2-b995aa3e5966
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01209773-4378-4bd7-881e-c29762f4395c
        userCondition: null
fs: covers
handle: bookcovers
name: BookCovers
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
