color: null
fieldLayouts:
  8f1c6a9b-2513-4c88-9739-85b45891f064:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ed7e3ef-32b9-47bc-bd8b-56173b993b8c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 58155d86-c55b-424a-967e-a479f429cd67
        userCondition: null
handle: authors
hasTitleField: true
icon: ''
name: Authors
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
