color: null
fieldLayouts:
  683fd9bb-1abf-47b4-ae65-79350eba1ab2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 10d995fe-2133-45ff-8352-5a3106528606
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 547c185a-e03a-43f4-92d5-54e0603ce28d
        userCondition: null
handle: genre
hasTitleField: true
icon: ''
name: Genre
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
