color: null
fieldLayouts:
  33485e8b-3926-4553-831b-63522d914da3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bfa8f328-0b46-41c8-a257-a236691f23a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34e5e530-cb96-470e-a108-fd34078dc8af # Hero afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff5efdad-7b83-4f09-9fc3-8aa454310804
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed4fc427-ba8c-48e3-a719-55b9c6471900 # AboutUs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66c2cfb9-a872-4fa6-b348-2ef1b7c8d965
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c399650-9339-4393-a2e0-c725d475930e
        userCondition: null
handle: homepage
hasTitleField: true
icon: ''
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
