color: null
fieldLayouts:
  afb94298-d2ca-4acc-b037-585597e8d538:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: acf30d9c-6a72-4343-9e23-24c2c268f288
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97a8f2ea-e095-4c6d-b4a2-1918b0bd6058 # Products Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b96436d9-a911-48e5-a41d-4148ff7fe4a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2df746e5-d0bc-4c70-8daf-af9dacaaf1f1
        userCondition: null
handle: overzichtspagina
hasTitleField: true
icon: ''
name: Overzichtspagina
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
