color: null
fieldLayouts:
  d2e971ff-6ba7-4433-890a-67e0897c1a39:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22af45a7-4a60-4986-8dc5-733c74b3a475
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 099aa5a2-2f17-4625-b19b-68c2c0870e2a # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9a13db2-88f4-4f14-b0d1-cc4dfa4ca98d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: db5b3729-7436-4bf0-8285-1ab5a943b829 #  Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95f4876c-0f26-48fd-9366-d073c551becb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 420b2873-fbbe-4338-bfd6-b53e97f2f166
        userCondition: null
handle: text
hasTitleField: true
icon: ''
name: 'Text + image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
