dateModified: 1716824244
email:
  fromEmail: 12000770@student.pxl.be
  fromName: Werkpakket3MK
  transportType: craft\mail\transportadapters\Sendmail
fs:
  covers:
    hasUrls: true
    name: Covers
    settings:
      path: '@webroot/files'
    type: craft\fs\Local
    url: /files
  files:
    hasUrls: true
    name: Bestanden
    settings:
      path: '@webroot/files'
    type: craft\fs\Local
    url: /files
meta:
  __names__:
    0eaf96d5-0ef4-43b6-97e2-90966eb0c57d: Authors # Authors
    4d849faf-00ba-47a6-a55d-4f272dc7871b: Startpagina # Startpagina
    5b788220-8937-4242-a0d3-e925cc1baa01: 'Profile Image' # Profile Image
    5c0cd73e-35c0-4b0b-af68-b06dc049dea7: Werkpakket3MK # Werkpakket3MK
    7f24352a-4648-4340-a010-59a6de936762: Profiel # Profiel
    8d4fc8c8-91d4-44f6-9480-39783cd823e0: Genre # Genre
    015f35b2-6849-4277-b9dc-2788aa0758bf: Authors # Authors
    29b8e0f7-a3f4-45ff-b287-67d4bfa84155: Bestanden # Bestanden
    34e5e530-cb96-470e-a108-fd34078dc8af: 'Hero afbeelding' # Hero afbeelding
    34f7cd61-8b11-48df-a0db-411aefc48529: 'Public Schema' # Public Schema
    43e6a80a-6b3b-4e9e-9d82-3979683bf0ae: BookCovers # BookCovers
    63f8ba1e-2ca9-4896-837c-2e420e1832ea: Contact # Contact
    074aab06-9f1d-445c-b3bd-0021dec41481: 'Product Detail' # Product Detail
    93a2d9f5-e92a-4f51-946e-d03ab611a8aa: Homepage # Homepage
    97a8f2ea-e095-4c6d-b4a2-1918b0bd6058: 'Products Image' # Products Image
    706c4c46-83f7-4f89-822e-2b163537378a: Authors # Authors
    2180c113-6968-495c-b80c-33a1de9a4f67: Books # Books
    2358d97c-4900-4980-b175-22759960966b: contact # contact
    3254cfc7-d5a2-4151-b8a8-5e799a93450e: Description # Description
    4601c264-f26e-47f9-9179-d929469357d1: Profiel # Profiel
    5295d502-c6ff-48e1-aeca-c3aeae76f674: Overzichtspagina # Overzichtspagina
    8026a632-47cd-479e-b10e-da70b61f068a: Genre # Genre
    b496724a-4f5b-448e-abf9-8c8a0fad49d7: Overzichtspagina # Overzichtspagina
    cb00a8c7-bd0e-4583-a31e-8ccf46b72369: 'Product Detail' # Product Detail
    d65b1f58-ebdc-4f21-a6b4-bf3c7b4b21e8: Price # Price
    d132d109-de40-4858-8e41-393bec88cb75: Books # Books
    db5b3729-7436-4bf0-8285-1ab5a943b829: ' Image' #  Image
    e52f1d17-a9bc-4097-b015-2da75e3f777b: Genre # Genre
    ed4fc427-ba8c-48e3-a719-55b9c6471900: AboutUs # AboutUs
    fbff62a5-6371-464d-8ade-3a325bcc94de: Werkpakket3MK # Werkpakket3MK
    fe9f12a0-0862-4a8e-9652-4e11f273e4f9: Bookauthor # Bookauthor
system:
  edition: solo
  live: true
  name: Werkpakket3MK
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
