fieldLayouts:
  dcc26faa-4f1d-488e-ab01-dc4039cef9a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 333e943e-6888-4e86-886c-125324f28623 # Instagram
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edb713b8-9322-4382-b60f-c722d88fe642
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2225d4e-3888-468f-a304-0d868b609e77 # Facebook
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7e5445b-ba49-496c-8460-f5a0828f0d2b
            userCondition: null
            warning: null
            width: 100
        name: Socials
        uid: e4616dd7-99c1-4b36-b07d-1b2bc73197e1
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 1
